name: Publish NPM

on:
release:
types: [published]

jobs:
publish-npm:
runs-on: ubuntu-latest

permissions:
  contents: read

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 22
      registry-url: https://registry.npmjs.org/

  - name: Install Dependencies
    run: npm install

  - name: Publish Package
    run: npm publish --access public
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
